### ISSUE TITLE
Error CurlMulti.php

### ISSUE THREAD

**Issue by Brijendrasial** [Toorop/ovh-sdk-php#33]
Getting the error below. How to fix it

Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message ' in C:\wamp\www\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php on line 561

Guzzle\Http\Exception\CurlException: [curl] 3: <url> malformed [url] /dedicated/server [info] array ( 'url' => '/dedicated/server', 'content_type' => NULL, 'http_code' => 0, 'header_size' => 0, 'request_size' => 0, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0, 'namelookup_time' => 0, 'connect_time' => 0, 'pretransfer_time' => 0, 'size_upload' => 0, 'size_download' => 0, 'speed_download' => 0, 'speed_upload' => 0, 'download_content_length' => -1, 'upload_content_length' => -1, 'starttransfer_time' => 0, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => '', 'certinfo' => array ( ), 'primary_port' => 0, 'local_ip' => '', 'local_port' => 0, ) [debug] in C:\wamp\www\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php on line 561

**Comment by Brijendrasial** [comment]
Fixed.

Missing endpoint/region in src/Ovh/Common/Auth/Keyring.php so added the line below.

elseif($Region == 'SYSCA'){
			return 'https://ca.api.soyoustart.com/1.0/';
		}

**Comment by Thibautg16** [comment]
C'est corrigé ;)
